// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBALoKV1I4Sb54S0qt_zJXj03LKCZcudE',
    appId: '1:568662285317:web:5d0dced25795765320d06c',
    messagingSenderId: '568662285317',
    projectId: 'notenest-c49c4',
    authDomain: 'notenest-c49c4.firebaseapp.com',
    storageBucket: 'notenest-c49c4.firebasestorage.app',
    measurementId: 'G-TXE73ZN2L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADe3PLltr_S0EFrYNxuM-Yh_RfF8MaW7k',
    appId: '1:568662285317:android:91d719884529406f20d06c',
    messagingSenderId: '568662285317',
    projectId: 'notenest-c49c4',
    storageBucket: 'notenest-c49c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBry5735wxcCXVdvMPEQntys0Ke2OcbJm8',
    appId: '1:568662285317:ios:e481ce71d9c4308120d06c',
    messagingSenderId: '568662285317',
    projectId: 'notenest-c49c4',
    storageBucket: 'notenest-c49c4.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBry5735wxcCXVdvMPEQntys0Ke2OcbJm8',
    appId: '1:568662285317:ios:e481ce71d9c4308120d06c',
    messagingSenderId: '568662285317',
    projectId: 'notenest-c49c4',
    storageBucket: 'notenest-c49c4.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBALoKV1I4Sb54S0qt_zJXj03LKCZcudE',
    appId: '1:568662285317:web:e829638fda0adf1920d06c',
    messagingSenderId: '568662285317',
    projectId: 'notenest-c49c4',
    authDomain: 'notenest-c49c4.firebaseapp.com',
    storageBucket: 'notenest-c49c4.firebasestorage.app',
    measurementId: 'G-R6M6V0ZC86',
  );

}